
package com.iti;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CDR", isSet = false )
    public class CDR implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "cdrId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String cdrId = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "callingNo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String callingNo = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "calledNo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String calledNo = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "cdrDate", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String cdrDate = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "consumption", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String consumption = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "startTime", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String startTime = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "serviceId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String serviceId = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "profileId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String profileId = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "callDuration", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String callDuration = null;
                
  
        
        public String getCdrId () {
            return this.cdrId;
        }

        

        public void setCdrId (String value) {
            this.cdrId = value;
        }
        
  
        
        public String getCallingNo () {
            return this.callingNo;
        }

        

        public void setCallingNo (String value) {
            this.callingNo = value;
        }
        
  
        
        public String getCalledNo () {
            return this.calledNo;
        }

        

        public void setCalledNo (String value) {
            this.calledNo = value;
        }
        
  
        
        public String getCdrDate () {
            return this.cdrDate;
        }

        

        public void setCdrDate (String value) {
            this.cdrDate = value;
        }
        
  
        
        public String getConsumption () {
            return this.consumption;
        }

        

        public void setConsumption (String value) {
            this.consumption = value;
        }
        
  
        
        public String getStartTime () {
            return this.startTime;
        }

        

        public void setStartTime (String value) {
            this.startTime = value;
        }
        
  
        
        public String getServiceId () {
            return this.serviceId;
        }

        

        public void setServiceId (String value) {
            this.serviceId = value;
        }
        
  
        
        public String getProfileId () {
            return this.profileId;
        }

        

        public void setProfileId (String value) {
            this.profileId = value;
        }
        
  
        
        public String getCallDuration () {
            return this.callDuration;
        }

        

        public void setCallDuration (String value) {
            this.callDuration = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CDR.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            